### ISSUE TITLE
Android 5.0  radius must be > 0 error

### ISSUE THREAD

**Issue by muhammedcobanoglu** [taoliuh/CardSlidePanel#1]
Hi, 
CardSlidePanel is running without problem under Android 5.0 but Android 5.0 doesn't work. That's error 

<img width="1184" alt="screen shot 2015-12-21 at 11 49 18" src="https://cloud.githubusercontent.com/assets/9548399/11927966/e44c11f6-a7d8-11e5-8d12-70d0f0456d90.png">

**Comment by taoliuh** [comment]
May be it's because of the background shape drawable. You can try to add radius.I don't know why, but it works fine on my nexus 5 which runs on android 6.0.

**Comment by muhammedcobanoglu** [comment]
It worked. I made comment line that code
//getWindow().setBackgroundDrawableResource(R.drawable.purple_gradient);
