### ISSUE TITLE
根据滑动的位置逐渐隐去滑动view。能否提供好的思路

### ISSUE THREAD

**Issue by wyb20151010** [taoliuh/CardSlidePanel#2]
我在原项目中onlayout中对子view进行ontouch事件监控，为何无用。。谢谢你的帮助

**Comment by taoliuh** [comment]
触摸事件不是在onLayout里处理的。所有的触摸事件都代理给ViewDragHelper里进行处理了，所以会回调onViewPositionChanged. 在processLinkageView方法里去修改顶层view的alpha属性。

**Comment by wyb20151010** [comment]
恩，我试试看O(∩_∩)O谢谢

**Comment by wyb20151010** [comment]
谢谢你的提示，实现了根据滑动的位置逐渐隐去滑动view的效果，前四页效果不错，但是为何我翻了四页后就不好了。
添加如下代码：
int alllength;
if (changeViewLeft < 0) {
            alllength = Math.abs(changeViewLeft) + 54;
            mCardSwipeListenter.onScroll(-alllength / 300f);
}
else if (changeViewLeft >= 0 && changeViewLeft < 54) {
 alllength = Math.abs(changeViewLeft);
mCardSwipeListenter.onScroll(-alllength / 300f);
}
else if (changeViewLeft > 54) {
alllength = Math.abs(changeViewLeft - 54);
mCardSwipeListenter.onScroll(alllength / 300f);
}
else if (changeViewLeft == 54) {
alllength = 0;
mCardSwipeListenter.onScroll(alllength / 300f);
}
和
public View getSelectedView(){
        return viewList.get(0);
 }
第5页直接无法显示，拖动点击才出来。求指教。。

**Comment by taoliuh** [comment]
因为你改变透明度属性了，view被回收的时候你需要reset

**Comment by wyb20151010** [comment]
请问view在哪里被回收啊。。。要怎么reset。。@taoliuh

**Comment by taoliuh** [comment]
``` java
orderViewStack 
```

方法里改变changedView的属性。代码不多，梳理一遍就懂了

**Comment by wyb20151010** [comment]
虽然我不太懂，但是我在orderViewStack,中加入
changedView.findViewById(R.id.ll_content).setAlpha(1f);
changedView.findViewById(R.id.iv_notlike).setAlpha(0f);
changedView.findViewById(R.id.iv_like).setAlpha(0f);
效果完美了，我继续看。。
非常感谢您的提醒和帮助@taoliuh

**Comment by wyb20151010** [comment]
你好，实际会需要当卡片到达最后时，怎么判断卡片到达最后呢？期待您的回答。。
